<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>flag</string>
	</array>
	<key>name</key>
	<string>Flag</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\\\\</string>
			<key>name</key>
			<string>source.flag</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\\[|~\\]</string>
			<key>name</key>
			<string>source.flag</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>~(.*?)\|</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.flag.key</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\|(.*?)~</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.flag.name</string>
				</dict>
			</dict>
			<key>name</key>
			<string>keyword.control.flag</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>source.flag</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.flag</string>
	<key>uuid</key>
	<string>7f039691-69d7-447e-8a60-fec2c764b59d</string>
</dict>
</plist>
